### ISSUE TITLE
"Sanering" er vel ikke riktig ord?

### ISSUE THREAD

**Issue by ahusby** [navikt/offentlig#1]
Ang. dokumentet "sanering.md": Tittelen (og filen) har feil navn, for teksten handler ikke om  sanering (sletting av repo) men om å kvalitetssikre det som legges i nye repos på Github.Misvisende tittel gjør det vanskelig å finne dokumentasjonen for de som trenger den.

**Comment by Starefossen** [comment]
Dette skal være fikset.
