### ISSUE TITLE
English

### ISSUE THREAD

**Issue by redblue-pkt** [navikt/offentlig#17]
I understand that this is official oil NAV. However, the English descriptions are missing, so I'd like to ask for an opossum in English. Why? Not everyone who lives in Norway and uses nav services knows Norwegian. I understand the code, but can the description be in English?

**Comment by Starefossen** [comment]
Sorry for the delayed answer @redblue-pkt, there are currently no plan to translate the guidelines to English as the working language internally at NAV is Norwegian. I would be happy to answer any questions here if you have any.
